// #ifndef INI_IMPLEMENTATION
// #define INI_IMPLEMENTATION
// #endif // INI_IMPLEMENTATION

#ifndef NK_IMPLEMENTATION
#define NK_INCLUDE_FIXED_TYPES
#define NK_INCLUDE_STANDARD_IO
#define NK_INCLUDE_DEFAULT_ALLOCATOR
#define NK_INCLUDE_VERTEX_BUFFER_OUTPUT
#define NK_INCLUDE_FONT_BAKING
#define NK_INCLUDE_DEFAULT_FONT
#define NK_INCLUDE_STANDARD_VARARGS
#define NK_IMPLEMENTATION
#endif // NK_IMPLEMENTATION

#ifndef SOKOL_NUKLEAR_IMPL
#define SOKOL_NUKLEAR_IMPL
#endif // SOKOL_NUKLEAR_IMPL

#ifndef SOKOL_APP_IMPL
#define SOKOL_APP_IMPL
#endif // SOKOL_APP_IMPL

#ifndef SOKOL_AUDIO_IMPL
#define SOKOL_AUDIO_IMPL
#endif // SOKOL_AUDIO_IMPL

#ifndef SOKOL_GFX_IMPL
#define SOKOL_GFX_IMPL
#endif // SOKOL_GFX_IMPL

#ifndef SOKOL_GL_IMPL
#define SOKOL_GL_IMPL
#endif // SOKOL_GL_IMPL

#ifndef SOKOL_GLUE_IMPL
#define SOKOL_GLUE_IMPL
#endif // SOKOL_GLUE_IMPL

#include "libs.h"
